### ISSUE TITLE
Wrong title

### ISSUE THREAD

**Issue by saberraz** [datagistips/30DayMapFailChallenge#4]
You have 30 days but there are only 28(+1) days in February. Unless this is already a part of the Map Failburary!
A quick suggestion, as a motto, you can have:  **All maps are wrong, but some are more wrong**

**Comment by datagistips** [comment]
corrected !

Also, I added your idea to the wish list : https://github.com/datagistips/MapFailbruaryChallenge/commit/5dc77314ac03a78d5420b3dcc74d9f2374db909f

There is an idea which resembles, and that will appear in the challenge. It's "Source : trust me bro" ;-)
